import Head from 'next/head'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import Comentar from '../components/Comentar'
import Feature from '../components/Feature'
import Theme from '../components/Theme'
import Paket from '../components/Paket'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Weddin Story</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <Navbar />
      <Hero />
      <Comentar />
      <Feature />
      <Theme />
      <Paket />
      <Footer />
  
    </div>
  )
}
